In [1]:
import numpy as np

In [3]:
tmp_a = np.array([[1, 2, 3], [1, 2, 3]])
tmp_b = np.array([[4, 5, 6], [4, 5, 6]])
tmp_a * tmp_b

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [16]:
tmp = np.array([1, 2, 0])

In [17]:
eye_mat = np.eye(3)
eye_mat[tmp, :].astype(np.float32)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [21]:
tmp[::2]

array([1, 0])

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.8.0-dev20180329
