In [1]:
import numpy as np

In [3]:
tmp_a = np.array([-0.42, 0.42, 0.42, -1.2])
tmp_a

array([-0.42,  0.42,  0.42, -1.2 ])

In [5]:
tmp_a = np.tile(tmp_a, (3, 1))
tmp_a

array([[-0.42,  0.42,  0.42, -1.2 ],
       [-0.42,  0.42,  0.42, -1.2 ],
       [-0.42,  0.42,  0.42, -1.2 ]])

In [12]:
tmp_b = np.array([0, 0, 0, 1])
np.dot(tmp_a, tmp_b)

array([ 0.56,  0.56,  0.56])

In [14]:
tmp_b.shape

(4,)

In [3]:
from scipy.special import expit

In [5]:
tmp_a = np.array([0., 1.46, 1.1])
expit(tmp_a)

array([ 0.70056714,  0.81153267,  0.75026011])

In [6]:
tmp_b = np.array([[0.37, 0.97, 0.83], [0.39, 0.28, 0.65], [0.64, 0.09, 0.33], [0.91, 0.32, 0.14]])
tmp_b

array([[ 0.37,  0.97,  0.83],
       [ 0.39,  0.28,  0.65],
       [ 0.64,  0.09,  0.33],
       [ 0.91,  0.32,  0.14]])

In [10]:
tmp = np.dot(tmp_b, expit(tmp_a))
tmp

array([ 1.66911242,  0.9881194 ,  0.76898675,  1.00224297])

In [9]:
def softmax_minus_max(x):
    max_x = np.max(x)
    x -= max_x
    x_exp = np.exp(x)
    
    return x_exp / np.sum(x_exp)

In [11]:
softmax_minus_max(tmp)

array([ 0.41221037,  0.20862551,  0.16757117,  0.21159295])

In [6]:
tmp_a.flatten()

array([-0.42,  0.42,  0.42, -1.2 , -0.42,  0.42,  0.42, -1.2 , -0.42,
        0.42,  0.42, -1.2 ])

In [10]:
?tmp_a.flatten

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method
