In [1]:
import tensorflow as tf
import numpy as np
import time

In [2]:
tf.InteractiveSession()

In [3]:
a = tf.zeros((2, 2))
print(a.eval())

[[0. 0.]
 [0. 0.]]


In [4]:
x1 = tf.constant([1, 2, 3, 4])
x2 = tf.constant([5, 6, 7, 8])

result = tf.multiply(x1, x2)
print(result.eval())

[ 5 12 21 32]


In [7]:
sess = tf.Session()
coef = np.array([[1], [6], [9]])

w = tf.Variable(0, dtype=tf.float32)
x = tf.placeholder(shape=(3, 1), dtype=tf.float32)

cost = w**2 * x[0] + w * x[1] + x[2]
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# ony use when haing tf.Variable
init = tf.global_variables_initializer()
sess.run(init)

it = 1000
for _ in range(it):
    sess.run(train, feed_dict={x: coef})
    
print(sess.run(w))
print(sess.run(cost, feed_dict = {x: coef}))

sess.close()    

-2.9999943
[0.]


In [13]:
?tf.global_variables_initializer()

Signature: tf.global_variables_initializer()
Docstring:
Returns an Op that initializes global variables.

This is just a shortcut for `variables_initializer(global_variables())`

Returns:
  An Op that initializes global variables in the graph.
File:      d:\anaconda2\envs\tsf36\lib\site-packages\tensorflow\python\ops\variables.py
Type:      function


In [9]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [7]:
tot_production = [100, 101, 112, 122, 124, 122, 143, 152, 151, 126, 155, 159, 153, 177, 184, 169, 189, 225, 227, 223, 218, 231, 179, 240]
labor = [100, 105, 110, 117, 122, 121, 125, 134, 140, 123, 143, 147, 148, 155, 156, 152, 156, 183, 198, 201, 196, 194, 146, 151]
capital_input = [100, 107, 114, 122, 131, 138, 149, 163, 176, 185, 198, 208, 216, 226, 236, 244, 266, 298, 335, 366, 387, 407, 417, 431]

cobb_douglas = pd.DataFrame({
    'Total_Production': tot_production,
    'Labor_Input': labor,
    'Capital_Input': capital_input
})

cobb_douglas.head()

Capital_Input  Labor_Input  Total_Production
0            100          100               100
1            107          105               101
2            114          110               112
3            122          117               122
4            131          122               124

In [8]:
cobb_douglas = cobb_douglas.apply(lambda col_values: np.log10(col_values), axis=1)
cobb_douglas.head()

Capital_Input  Labor_Input  Total_Production
0       2.000000     2.000000          2.000000
1       2.029384     2.021189          2.004321
2       2.056905     2.041393          2.049218
3       2.086360     2.068186          2.086360
4       2.117271     2.086360          2.093422

In [22]:
regr = LinearRegression()
regr.fit(cobb_douglas.iloc[:, 0:-1], cobb_douglas.iloc[:, -1])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
regr.coef_

array([0.29521163, 0.66417415])

In [24]:
regr.intercept_

0.08488444838210185

In [25]:
regr.coef_[0] + regr.coef_[1]

0.9593857791199916