# From numpy, list

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
tf.convert_to_tensor(np.ones([2, 3]))

<tf.Tensor: id=49, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [0]:
tf.convert_to_tensor(np.zeros([2, 3]))

<tf.Tensor: id=51, shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [0]:
tf.convert_to_tensor([1, 2])

<tf.Tensor: id=53, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

# tf.zeros

In [0]:
a = tf.zeros([2, 3])

# tf.zeros_like

In [0]:
tf.zeros_like(a)

<tf.Tensor: id=66, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

# tf.fill

In [0]:
tf.fill([2, 2], 0.)

<tf.Tensor: id=74, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

# tf.random

In [0]:
tf.random.normal([2, 2], mean=1, stddev=1)

<tf.Tensor: id=81, shape=(2, 2), dtype=float32, numpy=
array([[1.7085483 , 2.3613663 ],
       [1.4203386 , 0.91462946]], dtype=float32)>

In [0]:
# https://assessingpsyche.wordpress.com/2014/06/04/using-the-truncated-normal-distribution/
tf.random.truncated_normal([2, 2])

<tf.Tensor: id=88, shape=(2, 2), dtype=float32, numpy=
array([[ 0.7902417,  0.8423269],
       [-1.7637302,  0.6950322]], dtype=float32)>

In [0]:
b = tf.constant([0, 1])
tf.cast(b, dtype=tf.bool)

<tf.Tensor: id=14, shape=(2,), dtype=bool, numpy=array([False,  True])>

# tf.Variable

In [0]:
a = tf.range(5)
b = tf.Variable(a)
print(b.dtype)
print(b.name)
print(b.trainable)
print(b.numpy())

<dtype: 'int32'>
Variable:0
True
[0 1 2 3 4]


In [0]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)

In [0]:
idx

<tf.Tensor: id=106, shape=(10,), dtype=int32, numpy=array([7, 1, 6, 8, 4, 5, 0, 2, 3, 9], dtype=int32)>

In [0]:
b = tf.random.normal([10])
print(b)

tf.Tensor(
[ 0.30402645  0.04102645  1.827063    0.2556292   0.79209304  2.4785826
 -1.689666   -0.23342058  0.66996884 -0.34534493], shape=(10,), dtype=float32)


In [0]:
b_1 = tf.gather(b, idx) # equivalent to b = np.array([2, 5, 6, 9]), idx = [2, 1, 0, 3] --> b[idx] = np.array([6, 5, 2, 9])
print(b_1)

tf.Tensor(
[-0.23342058  0.04102645 -1.689666    0.66996884  0.79209304  2.4785826
  0.30402645  1.827063    0.2556292  -0.34534493], shape=(10,), dtype=float32)


In [0]:
b_1

<tf.Tensor: id=109, shape=(10,), dtype=float32, numpy=
array([-0.42398933,  0.5387916 ,  1.1074581 ,  0.5014956 ,  0.7389524 ,
        0.22786121,  1.7052184 ,  0.38056594,  1.345198  ,  0.18721788],
      dtype=float32)>

In [0]:
b

<tf.Tensor: id=100, shape=(10,), dtype=float32, numpy=
array([ 1.7052184 ,  0.5387916 ,  0.38056594,  1.345198  ,  0.7389524 ,
        0.22786121,  1.1074581 , -0.42398933,  0.5014956 ,  0.18721788],
      dtype=float32)>

In [0]:
from tensorflow.keras import layers

# Create kernel and bias

In [0]:
x = tf.random.normal([4, 784])

net = layers.Dense(10)
net.build((4, 784))

In [0]:
net.kernel

<tf.Variable 'kernel:0' shape=(784, 10) dtype=float32, numpy=
array([[ 0.06972524, -0.00441265, -0.04061479, ...,  0.03950334,
        -0.077971  , -0.01086161],
       [ 0.00488394,  0.07651331, -0.08168378, ..., -0.06282382,
        -0.03743479,  0.08679696],
       [-0.04640407, -0.01665675,  0.04548831, ...,  0.04844909,
        -0.00345407,  0.06951759],
       ...,
       [ 0.02807427, -0.0715555 ,  0.00650156, ..., -0.07030544,
        -0.08236653, -0.05510021],
       [ 0.05131801,  0.02043574, -0.08541578, ..., -0.08261286,
        -0.05360834,  0.063302  ],
       [-0.06280925, -0.04804197, -0.08084955, ..., -0.02112252,
        -0.06687539, -0.04175954]], dtype=float32)>

In [0]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [0]:
net(x).shape

TensorShape([4, 10])